-- UYGULANMADI. Tek satir, additive, geriye donuk uyumlu.
-- Calistirilacak SQL:
--
--   ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS baseline_net numeric(5,2);
--
-- NEDEN GEREKLI
-- Tasarimin "Seviye Testi" ekrani (onboarding 3/4) ders basina yalniz NET
-- soruyor ve amacini kendi metninde soyluyor:
--   "Son denemeni gir, rotanin BASLANGIC NOKTASINI oradan cizelim."
-- Rota Hazir ekrani da bunu "BUGUN · 58,25" olarak gosteriyor.
--
-- NEDEN DENEME KAYDI OLARAK SAKLANMIYOR
-- CANLI DOGRULAMA (2026-09-10): public.trial_subjects kolonlari
--   id, trial_id, subject, correct_count, wrong_count, empty_count,
--   wrong_penalty numeric, net numeric GENERATED ALWAYS AS
--   (COALESCE(correct_count,0) - COALESCE(wrong_count,0) * ...) STORED
-- (Not: wrong_penalty kolonu migration dosyalarinda YOK, yalnizca canlida var.)
--
-- net GENERATED oldugu icin dogrudan yazilamiyor, D/Y uzerinden ifade etmek
-- zorunlu. Ilk uygulama `correct = round(net), wrong = 0` yaziyordu; bu
-- "kullanici hic yanlis yapmadi" iddiasi demek ve uc tuketiciyi yaniltiyor:
--   useAISuggestions      -> dogruluk orani  (correct/(correct+wrong))
--   useWeeklyTrialReport  -> haftalik yanlis toplami
--   trialKeyMap           -> total = correct + wrong
--
-- net'i duz kolona cevirmek mumkun ama create_trial RPC'sinin de yeniden
-- yazilmasini gerektiriyor (generated kolon kalkinca net'i RPC hesaplamak
-- zorunda) — production'in deneme yazma yolu, ayri ve dikkatli bir is.
--
-- Bu yuzden baslangic neti KENDI ALANINDA tutuluyor: uydurma D/Y yok,
-- tasarimin ekrani da aynen kaliyor. Tasarimin kendi kurali bunu destekliyor:
-- "Bir denemeyle rota cizilir, egilim cizilmez" — tek veri noktasi zaten
-- trend uretmiyor, dolayisiyla deneme kaydi olmasi gerekmiyor.
--
-- UYGULANDIKTAN SONRA
-- ExamContext.updateBaselineNet zaten profiles.baseline_net'e yaziyor;
-- kolon gelene kadar deger yalnizca cihazda tutuluyor.
