-- UYGULANMADI. Canli DB'ye elle uygulanmasi gerekiyor.
--
-- BULGU (FAZ 1.2 sema farki, 2026-09-10):
-- Tasarimin onboarding 1. adimi HEDEF NET soruyor — slider 40-120, varsayilan 72,
-- etiket "net · TYT" (artboard "Hedef Sec", ilerleme gostergesi "1 / 4").
-- Sonraki adimlar bu degeri kullaniyor:
--   "Seviye Testi": "Hedefe 13,75 net var. Bu mesafe 9 aylik bir rota demek."
--   "Rota Hazir":   "BUGUN · 58,25"  /  "HEDEF · 72"
--
-- Kodda bu deger HICBIR YERDE SAKLANMIYOR:
--   - profiles'ta target_ranking ve daily_question_goal var, target_net YOK
--   - ExamContext targetRanking/targetDepartment tutuyor, targetNet tutmuyor
--   - targetNet yalnizca thresholdGap(routeEngine.js:239) parametresi olarak
--     yasiyor, cagiran taraftan geciyor ve hicbir yere yazilmiyor
--
-- Not: "gunluk soru 20-200" (daily_question_goal) bunun karsiligi DEGIL —
-- o buildRoute'a kapasite girdisi olarak gidiyor. Ikisi ayri sey, ikisi de gerekli.

-- CANLI DOGRULAMA (2026-09-10, Supabase SQL editoru, proje zrycqfehhyjrsujmajpf):
--   profiles = 30 kolon. Hedefle ilgili olanlar TAM OLARAK sunlar:
--     daily_question_goal integer · daily_target integer
--     target_department text   · target_ranking text
--   target_net YOK. Dogrulandi, varsayim degil.
--   (Ayrica not: daily_target ve daily_question_goal ikisi de duruyor —
--    biri muhtemelen olu, ayri bir temizlik isi.)
--
-- UYGULAMADAN ONCE yine de RLS politikalarinin kullanicinin kendi satirini
-- guncellemeye izin verdigini DOGRULA.

-- ALTER TABLE public.profiles
--   ADD COLUMN IF NOT EXISTS target_net numeric(5,2);
--
-- Tasarimdaki slider araligi: 40-120. Sinav turune gore ust sinir degisiyor
-- (TYT 120, AYT ders sayisina bagli), o yuzden kisit uygulama tarafinda
-- kalabilir; DB'de yalnizca makul bir taban:
-- ALTER TABLE public.profiles
--   ADD CONSTRAINT profiles_target_net_range
--   CHECK (target_net IS NULL OR (target_net >= 0 AND target_net <= 500));

-- SONRA istemci tarafi:
--   ExamContext: targetNet state + updateTargetNet, profiles.target_net'e yaz
--   Hedef Sec ekrani: slider degerini oraya bagla
--   Rota Hazir / Seviye Testi: hedefi oradan oku (su an sabit deger gosteriyor)
