export const PRODUCT_FLOW_IDS = {
  DAILY_LOOP: "daily_loop",
  ROUTE_DEPTH: "route_depth",
  QUICK_ENTRY: "quick_entry",
  TRIAL_CAPTURE: "trial_capture",
  ANALYSIS_NOTEBOOK: "analysis_notebook",
  WRONG_NOTEBOOK: "wrong_notebook",
  PLAN_STOPS: "plan_stops",
  STUDY_SESSION: "study_session",
  PROFILE: "profile",
  SOCIAL: "social",
  SETTINGS: "settings",
  ONBOARDING: "onboarding",
  PREMIUM: "premium",
  TIME_BASED: "time_based",
  SYSTEM_STATE: "system_state",
};

export const PRODUCT_FLOWS = [
  {
    id: PRODUCT_FLOW_IDS.DAILY_LOOP,
    order: 1,
    label: "Daily loop",
    designCount: 8,
    designScreens: [
      "Home",
      "Study session",
      "Session complete",
      "Next step",
      "Streak calendar",
      "Daily summary",
      "Weekly summary",
      "Monthly summary",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.ROUTE_DEPTH,
    order: 2,
    label: "Route depth",
    designCount: 8,
    designScreens: [
      "Route detail",
      "Full route",
      "Stop detail",
      "Pause route",
      "Frozen route",
      "Scenarios",
      "Program threshold",
      "Redraw route",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.QUICK_ENTRY,
    order: 3,
    label: "Quick entry",
    designCount: 6,
    designScreens: [
      "Quick add",
      "Trial entry 1",
      "Trial entry 2",
      "Trial entry 3",
      "Return to photo",
      "Trial detail",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.TRIAL_CAPTURE,
    order: 4,
    label: "Trial capture variants",
    designCount: 6,
    designScreens: [
      "Photo OCR",
      "OCR confirmation",
      "Measured study record",
      "Manual study record",
      "Edit record",
      "Trial summary",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.ANALYSIS_NOTEBOOK,
    order: 5,
    label: "Analysis and notebook",
    designScreens: [
      "Analysis",
      "Trial records",
      "Topic analysis",
      "Wrong notebook",
      "Priority topics",
      "Trial comparison",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.WRONG_NOTEBOOK,
    order: 6,
    label: "Wrong notebook flow",
    designScreens: ["Add wrong", "Wrong detail", "Question detail", "Review", "Review complete"],
  },
  {
    id: PRODUCT_FLOW_IDS.PLAN_STOPS,
    order: 7,
    label: "Plan and stops",
    designScreens: [
      "Roadmap",
      "Program",
      "Weekly program",
      "Calendar",
      "Add stop",
      "Topic detail",
      "Course topics",
      "Topic debt",
      "Plan vs actual",
      "Debt redistributed",
      "Catch-up plan",
      "Monthly plan",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.STUDY_SESSION,
    order: 8,
    label: "Study session details",
    designScreens: ["Tag session", "Recovered session", "Study history", "Lock screen"],
  },
  {
    id: PRODUCT_FLOW_IDS.PROFILE,
    order: 9,
    label: "Profile",
    designScreens: ["Profile", "Level", "Milestone", "Share card", "Card modes"],
  },
  {
    id: PRODUCT_FLOW_IDS.SOCIAL,
    order: 10,
    label: "Social",
    designScreens: ["Community", "League", "Invite", "Search", "Ask question", "Reply"],
  },
  {
    id: PRODUCT_FLOW_IDS.SETTINGS,
    order: 11,
    label: "Settings",
    designScreens: [
      "Settings",
      "Edit profile",
      "Notifications",
      "Appearance",
      "Privacy",
      "Document",
      "Export data",
      "Delete account",
      "Edit goal",
      "Date picker",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.ONBOARDING,
    order: 12,
    label: "Account and setup",
    designScreens: [
      "Welcome",
      "Login",
      "Register",
      "Forgot password",
      "Email sent",
      "Goal select",
      "Programs",
      "Preference list",
      "Level test",
      "Route ready",
      "Notification permission",
      "System permission",
      "First day",
      "Setup abandoned",
    ],
  },
  {
    id: PRODUCT_FLOW_IDS.PREMIUM,
    order: 13,
    label: "Premium",
    designScreens: ["Paywall moment", "Premium", "Subscription", "Cancel subscription"],
  },
  {
    id: PRODUCT_FLOW_IDS.TIME_BASED,
    order: 14,
    label: "Time based states",
    designScreens: [
      "Last week",
      "Exam day",
      "Comeback",
      "After last week",
      "Exam day plan",
      "Exam result",
      "Prediction accuracy",
      "Prediction missed",
      "Trial rehearsal",
    ],
  },
];

export function getProductFlow(flowId) {
  return PRODUCT_FLOWS.find((flow) => flow.id === flowId) || null;
}
