// Maraton Design Tokens v4
// Source: redesign system board. Dark-only foundation for the route-era UI.

export const DESIGN_TOKENS = {
  mode: "dark",
  color: {
    ink: "#171C23",
    surface: "#25262F",
    surfaceElevated: "#30303B",
    border: "#52403B",
    line: "rgba(255,255,255,0.08)",
    lineSoft: "rgba(255,255,255,0.05)",

    brand: "#EC3347",
    brandPressed: "#C92839",
    brandSoft: "rgba(236,51,71,0.16)",

    up: "#30D98A",
    down: "#A7B7C5",
    warn: "#F7C44A",
    text: "#F5F7FA",
    textSecondary: "#A7B0BD",
    textMuted: "#6F7785",
    textOnBrand: "#FFFFFF",

    subject: {
      turkce: "#58A7FA",
      matematik: "#FF9F2E",
      fizik: "#2BD4EA",
      kimya: "#E66BB6",
      biyoloji: "#42D98C",
      tarih: "#F7C44A",
      cografya: "#2DD4BF",
      felsefe: "#A78BFA",
      din: "#8DDC3A",
      sosyal: "#A78BFA",
      fen: "#30D98A",
      edebiyat: "#E66BB6",
      ingilizce: "#7DD3FC",
    },
  },
  radius: {
    xs: 6,
    sm: 8,
    md: 10,
    lg: 14,
    xl: 18,
    xxl: 22,
    pill: 999,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    page: 18,
  },
  typography: {
    display: { fontFamily: "SpaceGrotesk_700Bold", fontSize: 56, lineHeight: 58, letterSpacing: 0 },
    h1: { fontFamily: "SpaceGrotesk_700Bold", fontSize: 28, lineHeight: 32, letterSpacing: 0 },
    h2: { fontFamily: "SpaceGrotesk_700Bold", fontSize: 22, lineHeight: 27, letterSpacing: 0 },
    body: { fontFamily: "Inter_400Regular", fontSize: 14, lineHeight: 20, letterSpacing: 0 },
    bodyStrong: { fontFamily: "Inter_600SemiBold", fontSize: 14, lineHeight: 20, letterSpacing: 0 },
    label: { fontFamily: "Inter_700Bold", fontSize: 10, lineHeight: 13, letterSpacing: 0.6 },
    stat: { fontFamily: "SpaceGrotesk_700Bold", fontSize: 42, lineHeight: 46, letterSpacing: 0 },
    statSmall: { fontFamily: "SpaceGrotesk_700Bold", fontSize: 24, lineHeight: 28, letterSpacing: 0 },
  },
};

export function legacyPaletteFromDesignTokens() {
  const c = DESIGN_TOKENS.color;
  return {
    bg: c.ink,
    surface: c.surface,
    surface2: c.surfaceElevated,
    border: c.line,
    borderSoft: c.lineSoft,
    amber: c.subject.matematik,
    green: c.up,
    yellow: c.warn,
    red: c.brand,
    teal: c.subject.cografya,
    purple: c.subject.felsefe,
    blue: c.subject.turkce,
    pink: c.subject.kimya,
    coral: c.brand,
    accent: c.brand,
    accentLight: c.brandSoft,
    accentDark: c.brandPressed,
    brandLight: "#FF6B78",
    orange: c.brand,
    orangeLight: c.brandSoft,
    success: c.up,
    danger: c.brand,
    warning: c.warn,
    info: c.subject.turkce,
    text: c.text,
    sec: c.textSecondary,
    muted: c.textMuted,
    cream: c.text,
    dormant: "rgba(255,255,255,0.24)",
    dormantBg: "rgba(255,255,255,0.05)",
    textOnBrand: c.textOnBrand,
    textOnAccent: c.textOnBrand,
    textOnFill: c.textOnBrand,
    accentPressed: c.brandPressed,
    orangePressed: c.brandPressed,
    surfacePressed: "rgba(255,255,255,0.06)",
  };
}

